### ISSUE TITLE
Chromecast built in...

### ISSUE THREAD

**Issue by shawaj** [googlecast/CastReceiver#22]
Is it possible to apply for the "Chromecast built in" program? https://www.google.com/chromecast/built-in/audio/

We would like to add the ability to cast to our speakers.

**Comment by robotal** [comment]
Just stumbled across chromecast built-in and it seems like exactly what I'm looking for. We would like to integrate our home network speakers with the youtube music app to be able to cast music to a raspberry pi similar to how spotify lets you stream audio to an arbitrary server. 

My understanding from looking over the readme for this project is the YTM app wouldn't be able to connect to a custom receiver because it is not aware of its app id. Let me know if I'm missing something though.

**Comment by jtromo** [comment]
Please submit your questions to the support page: https://support.google.com/chromecast/gethelp?visit_id=637535192519667801-2123706460&rd=1

These issues are reserved for bugs related to the samples.
